### ISSUE TITLE
error: {standard input}: Assembler messages

### ISSUE THREAD

**Issue by eko5624** [lhmouse/MINGW-packages#12]
When compiling aom, I get this error. Any help would be great.
https://github.com/eko5624/mpv-win64/actions/runs/6858299205/job/18648815957

[logs_5086.zip](https://github.com/lhmouse/mcfgthread/files/13344032/logs_5086.zip)

But his build no error.
https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0mcf-16.0.6-11.0.1-ucrt-r2/winlibs-x86_64-mcf-seh-gcc-13.2.0-mingw-w64ucrt-11.0.1-r2.7z

**Comment by lhmouse** [comment]
It's because some code has inline assembly in AT&T syntax. My toolchains use Intel syntax, so you will need to pass `-masm=att` in `CPPFLAGS`, or in `CFLAGS` and `CXXFLAGS`.

**Comment by eko5624** [comment]
Follow your guide, it works now. Thanks.
