### ISSUE TITLE
gcc package missing make depends

### ISSUE THREAD

**Issue by stahta01** [lhmouse/MINGW-packages#13]
I think "${MINGW_PACKAGE_PREFIX}-mcfgthread" needs added to makedepends for mingw-w64-gcc.

I built it and the build failed in libgcc because it failed to find gthr.h under mcfgthread folder.

Tim S.

**Comment by lhmouse** [comment]
Thanks. Makes sense.

**Comment by lhmouse** [comment]
Untested: https://github.com/lhmouse/MINGW-packages/commit/cbaa121c5d3f35e312be7fcf956c70ee4d2075ca#diff-cf683a120abf18dd9f774ea5df77137d01e19f359f7cb40c1fc152355cde7b80R51
