### ISSUE TITLE
gcc prepare git clean possible issue

### ISSUE THREAD

**Issue by stahta01** [lhmouse/MINGW-packages#14]
The git call in prepare()
`git clean -fdx`
likely should be
`git clean -fdX`

Tim S.

**Comment by lhmouse** [comment]
There are occasional patches in plain diff format instead of mbox format, which are applied with `git apply -3` or `patch --merge`, which does not commit the changes and may leave untracked files behind. The `x` in lowercase ensures a clean work tree is prepared for the other patches.

**Comment by stahta01** [comment]
> There are occasional patches in plain diff format instead of mbox format, which are applied with `git apply -3` or `patch --merge`, which does not commit the changes and may leave untracked files behind. The `x` in lowercase ensures a clean work tree is prepared for the other patches.

Per git docs the lower x requires the e option; the directions implies it does nothing if no e option is used.
Note: I have not confirmed the directions is correct.

Tim S.

**Comment by lhmouse** [comment]
> Per git docs the lower x requires the e option; the directions implies it does nothing if no e option is used. Note: I have not confirmed the directions is correct.

Actually I have been using `git clean -fdx` for many years and have not been aware of `-e`. The Git manual says  

> -e <pattern>, --exclude=<pattern>
>    Use the given exclude pattern **in addition** to the standard ignore rules (see gitignore(5)).

Since we are not adding ignore rules, it doesn't seem to be necessary.

**Comment by stahta01** [comment]
> > Per git docs the lower x requires the e option; the directions implies it does nothing if no e option is used. Note: I have not confirmed the directions is correct.
> 
> Actually I have been using `git clean -fdx` for many years and have not been aware of `-e`. The Git manual says
> 
> > -e , --exclude=
> > Use the given exclude pattern **in addition** to the standard ignore rules (see gitignore(5)).
> 
> Since we are not adding ignore rules, it doesn't seem to be necessary.

`-x
Don’t use the standard ignore rules, but still use the ignore rules given with -e options from the command line. This allows removing all untracked files, including build products. This can be used (possibly in conjunction with git restore or git reset) to create a pristine working directory to test a clean build.`

I hope you are right.

Tim S.
