### ISSUE TITLE
Probable Ada build fix.

### ISSUE THREAD

**Issue by stahta01** [lhmouse/MINGW-packages#15]
```diff --git a/config/mh-mingw b/config/mh-mingw
index e91367a7112..c4796bf7b70 100644
--- a/config/mh-mingw
+++ b/config/mh-mingw
@@ -13,3 +13,5 @@ STAGE4_CXXFLAGS += -D__USE_MINGW_ACCESS
 # as GCC turns out to need that much more to pass all the limits-* tests.
 LDFLAGS += -Wl,--stack,12582912
 BOOT_LDFLAGS += -Wl,--stack,12582912
+
+ADA_CFLAGS = -masm=att
-- ```

It built for me here [intel_asm_syntax branch](https://github.com/stahta01/MINGW-packages/tree/intel_asm_syntax)
[arifacts](https://github.com/stahta01/MINGW-packages/actions/runs/7601551588)

For the CI servers to build I had to build the pkgrel else it errored out.

Tim S.

**Comment by lhmouse** [comment]
Well, I dont build Ada myself. However I would like to know what error it is.. 

I think I have to work https://gcc.gnu.org/PR53929 out by quoting symbols. The DWARF2 exception model is causing trouble, but I think I've found a solution, and am still testing my patch.

**Comment by stahta01** [comment]
> Well, I dont build Ada myself. However I would like to know what error it is..
> 
> I think I have to work https://gcc.gnu.org/PR53929 out by quoting symbols. The DWARF2 exception model is causing trouble, but I think I've found a solution, and am still testing my patch.

Ada requires AT&T assembly syntax; my patch fixes the error of "Error: invalid use of register" in stage 2 gcc building by using AT&T syntax in building Ada C code. Edit: The Ada/gnat team has documentation saying Ada uses AT&T syntax I read it as saying it only uses AT&T syntax.

Tim S.

**Comment by lhmouse** [comment]
Thanks for the suggestion. Squashed here:

https://github.com/lhmouse/MINGW-packages/commit/8ce160d6c651610aaadbd3b55bfd75a9e208d5dd#diff-a7d9f28e2e940168bf92a13d672ec159008e1bdf14f9f5a47db8288e4bab019aR20
