### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by basilisk0315** [lhmouse/MINGW-packages#2]
Hi lhmouse,

Firstly, thanks very much for your up to date builds of gcc. I have been using them to compile vim/gvim (x64) on windows for a while now and have had great success.
However, the latest build of gcc 9.2.1 (27-Aug-2019) throws this error when compiling GvimExt.dll:
make -C GvimExt -f Make_ming.mak CROSS=no CROSS_COMPILE= CXX='g++' STATIC_STDCPLUS=no                                                
make[1]: Entering directory 'U:/My Documents/Vim/vim/vim/src/GvimExt'                                                                
g++ -shared -O2 -s -o gvimext.dll \                                                                                                  
        -Wl,--enable-auto-image-base \                                                                                               
        -Wl,--enable-auto-import \                                                                                                   
        -Wl,--whole-archive \                                                                                                        
                gvimext.o gvimext.res gvimext_ming.def \                                                                             
        -Wl,--no-whole-archive \                                                                                                     
                -luuid -lgdi32                                                                                                       
c:/tmp/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/tmp/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/lib/../lib/libuuid.a(lib64_libuuid_a-uuid.o):uuid.c:(.rdata+0x640): multiple definition of `FMTID_ImageSummaryInformation'; gvimext.o:gvimext.cpp:(.rdata$FMTID_ImageSummaryInformation[FMTID_ImageSummaryInformation]+0x0)
: first defined here                                                                                                                 
c:/tmp/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/tmp/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/lib/../lib/libuuid.a(lib64_libuuid_a-uuid.o):uuid.c:(.rdata+0x650): multiple definition of `FMTID_MediaFileSummaryInformation'; gvimext.o:gvimext.cpp:(.rdata$FMTID_MediaFileSummaryInformation[FMTID_MediaFileSummaryInfor
mation]+0x0): first defined here                                                                                                     
c:/tmp/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/tmp/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/lib/../lib/libuuid.a(lib64_libuuid_a-uuid.o):uuid.c:(.rdata+0x660): multiple definition of `FMTID_AudioSummaryInformation'; gvimext.o:gvimext.cpp:(.rdata$FMTID_AudioSummaryInformation[FMTID_AudioSummaryInformation]+0x0)
: first defined here                                                                                                                 
collect2.exe: error: ld returned 1 exit status                                                                                       
make[1]: *** [Make_ming.mak:66: gvimext.dll] Error 1                                                                                 
make[1]: Leaving directory 'U:/My Documents/Vim/vim/vim/src/GvimExt'                                                                 
make: *** [Make_cyg_ming.mak:1051: GvimExt/gvimext.dll] Error 2                                                                      
make: Leaving directory 'U:/My Documents/Vim/vim/vim/src'

Copying libuuid.a from the previous release of 9.2.1 (13-aug-2019) into x86_64-w64-mingw32\lib directory of the latest release fixes the problem.
Cheers

**Comment by lhmouse** [comment]
在 2019/8/31 4:56, basilisk0315 写道:
> Hi lhmouse,
> 
> Firstly, thanks very much for your up to date builds of gcc. I have been
> using them to compile vim/gvim (x64) on windows for a while now and have
> had great success.
> However, the latest build of gcc 9.2.1 (27-Aug-2019) throws this error
> when compiling GvimExt.dll:
>   ....> make: Leaving directory 'U:/My Documents/Vim/vim/vim/src'
> 
> Copying libuuid.a from the previous release of 9.2.1 (13-aug-2019) into
> x86_64-w64-mingw32\lib directory of the latest release fixes the problem.
> Cheers
> 

This is due to commit 5a5a7c9322 in mingw-w64. All GUIDs in 'shlguid.h'
are defined in that header with `selectany` attribute so they are also
exported if you use `-Wl,--whole-archive` on the command line, which are
then redefinitions because libuuid already has them.




-- 
Best regards,
LH_Mouse

**Comment by basilisk0315** [comment]
Hi lhmouse,

A recent vim patch corrected the problem (patch 8.1.2025). It now builds cleanly.

Cheers
