### ISSUE TITLE
plugin link time optimization bug - multiple definition of dtor + non-virtual thunk

### ISSUE THREAD

**Issue by Xeverous** [lhmouse/MINGW-packages#4]
Hey, I'm posting it here because you do not have any strictly matching repository for GCC and since I encountered this problem using GCC with MCF you might be interested or at least help me localize who/what is responsible for this problem.

The bug is already described here: https://sourceforge.net/p/mingw-w64/bugs/829/

**Comment by lhmouse** [comment]
As **rubenvb** has pointed out it might be an LTO issue so I highly suggest you _not_ enable it. I was bit by it a few times back in GCC 4.9 days and I haven't been keeping an eye on it thereafter.

**Comment by Xeverous** [comment]
Yes, this is an LTO or binutils issue because it only happens with static library with LTO enabled. So far no success reproducing this on a smaller example. All I know now is that it happens in cerain conditions (Windows, static library, LTO, release) and affected code are only multiple-inheritance classes.

**Comment by Xeverous** [comment]
Just FYI, the problem accidentally reproduced on a Linux machine with GCC 9 when linking an example executable to a static library: https://github.com/cycfi/elements/pull/99/checks?check_run_id=639334740

Apparently LTO is currently more or less broken with GCC, even on Unix systems. I will definitely disable it for now in my projects. But it's good to see that the problem also reproduces on other distribution than yours.

**Comment by lhmouse** [comment]
Is this still an issue today?

I still do not recommend LTO for C++ due to the extensive use of weak/linkonce symbols. Without LTO https://github.com/lhmouse/asteria can compile and link in 1.5 minutes, but with LTO it would take more than an hour for only a couple of percentages of improvement about performance.

**Comment by Xeverous** [comment]
Technically, it is still an issue - LTO is not working. Disabling LTO hides the problem but I wonder if it can spill out to PGO and other, related things

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94156

Seems like the bug is outside your code (I think you can close it), it's probably a bug in MinGW's linker.
