### ISSUE TITLE
error during build

### ISSUE THREAD

**Issue by labba** [lhmouse/MINGW-packages#5]
after getting source 
git clone https://github.com/lhmouse/MINGW-packages.git

and then gotten the following error:

$ makepkg-mingw
==> Making package: mingw-w64-gcc-mcf 10.0.1.d20200507.c12.g0df8d1efee2-1 (Sun, Jun 21, 2020 11:51:22 PM)
==> Checking runtime dependencies...
==> Missing dependencies:
-> mingw-w64-x86_64-mcfgthread-libs
==> Checking buildtime dependencies...
==> Missing dependencies:
-> mingw-w64-x86_64-mcfgthread
==> ERROR: Could not resolve all dependencies.

**Comment by lhmouse** [comment]
You have to build and install it yourself:

```sh
cd mingw-w64-mcfgthread-git
makepkg-mingw
pacman -U *.tar.zst
```

**Comment by labba** [comment]
after applying your commands i have re-compile with your git the gcc 
this is the errors i get:

/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32/./gcc/xgcc -B/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32/./gcc/ -L/mingw64/x86_64-w64-mingw32/lib -L/mingw64/lib -isystem /mingw64/x86_64-w64-mingw32/include -isystem /mingw64/include -B/mingw64/x86_64-w64-mingw32/bin/ -B/mingw64/x86_64-w64-mingw32/lib/ -isystem /mingw64/x86_64-w64-mingw32/include -isystem /mingw64/x86_64-w64-mingw32/sys-include   -fno-checking -g -march=x86-64 -mtune=generic -O2 -pipe -O2 -I../../../gcc-git/libgcc/../winsup/w32api/include -g -march=x86-64 -mtune=generic -O2 -pipe -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-error=format-diag -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wno-error=format-diag -Wold-style-definition  -isystem ./include   -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -I. -I. -I../.././gcc -I../../../gcc-git/libgcc -I../../../gcc-git/libgcc/. -I../../../gcc-git/libgcc/../gcc -I../../../gcc-git/libgcc/../include -I../../../gcc-git/libgcc/config/libbid -DENABLE_DECIMAL_BID_FORMAT   -Wno-missing-prototypes -Wno-type-limits -o multf3.o -MT multf3.o -MD -MP -MF multf3.dep  -c ../../../gcc-git/libgcc/soft-fp/multf3.c
/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32/./gcc/xgcc -B/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32/./gcc/ -L/mingw64/x86_64-w64-mingw32/lib -L/mingw64/lib -isystem /mingw64/x86_64-w64-mingw32/include -isystem /mingw64/include -B/mingw64/x86_64-w64-mingw32/bin/ -B/mingw64/x86_64-w64-mingw32/lib/ -isystem /mingw64/x86_64-w64-mingw32/include -isystem /mingw64/x86_64-w64-mingw32/sys-include   -fno-checking -g -march=x86-64 -mtune=generic -O2 -pipe -O2 -I../../../gcc-git/libgcc/../winsup/w32api/include -g -march=x86-64 -mtune=generic -O2 -pipe -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-error=format-diag -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wno-error=format-diag -Wold-style-definition  -isystem ./include   -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -I. -I. -I../.././gcc -I../../../gcc-git/libgcc -I../../../gcc-git/libgcc/. -I../../../gcc-git/libgcc/../gcc -I../../../gcc-git/libgcc/../include -I../../../gcc-git/libgcc/config/libbid -DENABLE_DECIMAL_BID_FORMAT   -Wno-missing-prototypes -Wno-type-limits -o negtf2.o -MT negtf2.o -MD -MP -MF negtf2.dep  -c ../../../gcc-git/libgcc/soft-fp/negtf2.c
make[3]: *** [../../../gcc-git/libgcc/shared-object.mk:14: addtf3.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from ../../../gcc-git/libgcc/soft-fp/getf2.c:31:
../../../gcc-git/libgcc/soft-fp/soft-fp.h:42:11: fatal error: ./sfp-machine.h: Invalid argument
   42 | # include "sfp-machine.h"
      |           ^~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [../../../gcc-git/libgcc/shared-object.mk:14: divtf3.o] Error 1
In file included from ../../../gcc-git/libgcc/soft-fp/letf2.c:31:
../../../gcc-git/libgcc/soft-fp/soft-fp.h:42:11: fatal error: ./sfp-machine.h: Invalid argument
   42 | # include "sfp-machine.h"
      |           ^~~~~~~~~~~~~~~
compilation terminated.
In file included from ../../../gcc-git/libgcc/soft-fp/multf3.c:31:
../../../gcc-git/libgcc/soft-fp/soft-fp.h:42:11: fatal error: ./sfp-machine.h: Invalid argument
   42 | # include "sfp-machine.h"
      |           ^~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [../../../gcc-git/libgcc/shared-object.mk:14: eqtf2.o] Error 1
In file included from ../../../gcc-git/libgcc/soft-fp/negtf2.c:31:
../../../gcc-git/libgcc/soft-fp/soft-fp.h:42:11: fatal error: ./sfp-machine.h: Invalid argument
   42 | # include "sfp-machine.h"
      |           ^~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [../../../gcc-git/libgcc/shared-object.mk:14: getf2.o] Error 1
make[3]: *** [../../../gcc-git/libgcc/shared-object.mk:14: letf2.o] Error 1
make[3]: *** [../../../gcc-git/libgcc/shared-object.mk:14: multf3.o] Error 1
make[3]: *** [../../../gcc-git/libgcc/shared-object.mk:14: negtf2.o] Error 1
make[3]: Leaving directory '/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32/x86_64-w64-mingw32/libgcc'
make[2]: *** [Makefile:17959: all-stage1-target-libgcc] Error 2
make[2]: Leaving directory '/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32'
make[1]: *** [Makefile:21867: stage1-bubble] Error 2
make[1]: Leaving directory '/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32'
make: *** [Makefile:1009: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by expnkx** [comment]
https://bitbucket.org/ejsvifq_mabmip/mingw-gcc/src/master/

You can install this instead
https://bitbucket.org/ejsvifq_mabmip/mingw-gcc-mcfgthread-pacman/src/master/

**Comment by expnkx** [comment]
https://bitbucket.org/ejsvifq_mabmip/mingw-gcc-mcf-gthread/src/master/
Here is my build script

**Comment by labba** [comment]
thanks for the offer but i'm looking for a stable releases that are maintained and i can get it for older versions as well. 

i'm looking to build the gcc-8.4.0 after i will finish this and not the latest like you have in the links.

i fail to understand how this is working for others and what are the build setups they have that make the compilation work for them and this doesn't work for me.. 

i wish that someone would have done a clear step by step from a clean enviroment that doesn't have anything to get to a successful compilation .. 

i'm very educated on this subject and area but i always amazed that this area is never well documented on how to reproduce these compilation systems..

**Comment by lhmouse** [comment]
I have never seen the 'Invalid argument' errors. I suspect there is something wrong with your environment (for example if you build in CMD then Windows commands such as `find` and `sort` might interfere with the fragile scripts).

**Comment by labba** [comment]
i have installed msys2-x86_64-20200602
i'm running the shell that is located at : "C:\msys64\msys2.exe"

i'm NOT using windows CMD shell.

**Comment by lhmouse** [comment]
No idea how such errors happened. It looks like the preprocessor could not open the header file in question (this might happen when building other packages too). Would you please try a fresh re-installation of MSYS2?

**Comment by labba** [comment]
sure. 

done it now and you can see in the attached PDF every step i have done from installing msys2 until the failure.

[Step by step failure of compiling mingw with gcc latest.pdf](https://github.com/lhmouse/MINGW-packages/files/4820639/Step.by.step.failure.of.compiling.mingw.with.gcc.latest.pdf)


i would love to see such report form your side showing every steps and OS from clean environment until successful compilation (if possible)

**Comment by labba** [comment]
i have good update on this - in msys2 folder there is a need to edit the "msys2_shell.cmd" before executing it

there is a need to remove the "rem" from "set MSYS=winsymlinks:nativestrict"

this is the documentation of it:
"rem To activate windows native symlinks uncomment next line"

once done that, it seems to compile.


i'm re-building my report on how to compile this again and will upload it once i will reproduce again all the steps to make sure i haven't left out anything

**Comment by lhmouse** [comment]
I never use that script to start MSYS2. `mintty.exe` suffices. Upon launch it shows you three options so you may choose which shell to launch - msys2, mingw32 or mingw64. `msys2.exe`, `mingw32.exe` and `mingw64.exe` work too.

**Comment by labba** [comment]
well you never mentioned what you are running. or anything on your build environment setup...
when i run msys2.exe it got this compilation issues that was mentioned but only when running the cmd file with selected options it worked.

anyway, here is my step by step verified and updated. 

too bad none is doing such references on what they run and how.. it's important to see all steps from a clean environment until successful build. you can use it freely at your website as well if you want.. 

thanks for all the help and support!

Step by step compiling mingw with gcc latest lhmouse :
[Step by step compiling mingw with gcc latest lhmouse .pdf](https://github.com/lhmouse/MINGW-packages/files/4831878/Step.by.step.compiling.mingw.with.gcc.latest.lhmouse.pdf)

**Comment by lhmouse** [comment]
who is 'lmhouse'? :joy:

I have a Windows machine running **Windows 7 Professional** and I haven't received any `Invalid argument` issues so far. There is no tweak to any file. You may want to ask MSYS2 people about details of that option. I know nothing about it.

**Comment by labba** [comment]
😂 oops .. fixed and re-upload with typo fix.
