### ISSUE TITLE
resolving old gcc (8.3.0) compilation 

### ISSUE THREAD

**Issue by labba** [lhmouse/MINGW-packages#6]
hi,

i'm sorry for opening an issue but there is no chat or forum for that so i'm using this instead... 

i'm trying to build gcc 8.3.0 (since no repository for old mcfgthread) and also it's a good exercise :-)
so this is what i done:

1. git clone lhmouse 
2. find in "git log" the commit for 8.3.0 change update: 

commit 9fb1f4cdde77fa05d8226ce4637450e31c17cc2e
Author: Alexey Pavlov <alexpux@gmail.com>
Date:   Sat Feb 23 16:11:53 2019 +0300

    gcc: Update to 8.3.0

3. git checkout for commit number
4. compile mcfgthread depedency - went well
5. going to gcc-git folder trying to : "makepkg-mingw"

result:
remote: fatal: no such ref: refs/heads/gcc-8-branch

what is are the needed changes for PKGBUILD so i can get the 8.3.0 compilation work ?

**Comment by lhmouse** [comment]
The naming convention of release branches has changed in GCC repo. Refer to the current `PKGBUILD` and see how they are named now.

**Comment by labba** [comment]
looking on https://gcc.gnu.org/git/gcc.git active heads i see that it was changed to release so  i have changed it to point to "refs/heads/releases/" and changed the branch to "_branch=gcc-8"

like so:
_branch=gcc-8
_realpkgver="$(git archive --remote=git://gcc.gnu.org/git/gcc.git refs/heads/releases/${_branch}:gcc/ BASE-VER | tar -xO)"


after cloning i'm getting this error(i have tried others but getting the same issue):

# makepkg-mingw
==> Making package: mingw-w64-gcc-git r161609.3a2cb0e4437-1 (Sun, Jun 28, 2020 12:55:21 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning gcc git repo...
Cloning into bare repository '/home/labba/MINGW-packages/mingw-w64-gcc-git/gcc'...
remote: Enumerating objects: 2961, done.
remote: Counting objects: 100% (2961/2961), done.
remote: Compressing objects: 100% (1730/1730), done.
remote: Total 3400015 (delta 2152), reused 1454 (delta 1225), pack-reused 3397054
Receiving objects: 100% (3400015/3400015), 1.41 GiB | 7.21 MiB/s, done.
Resolving deltas: 100% (2672124/2672124), done.
  -> Found 0002-Relocate-libintl.patch
  -> Found 0003-Windows-Follow-Posix-dir-exists-semantics-more-close.patch
  -> Found 0004-Windows-Use-not-in-progpath-and-leave-case-as-is.patch
  -> Found 0005-Windows-Don-t-ignore-native-system-header-dir.patch
  -> Found 0006-Windows-New-feature-to-allow-overriding.patch
  -> Found 0007-Build-EXTRA_GNATTOOLS-for-Ada.patch
  -> Found 0008-Prettify-linking-no-undefined.patch
  -> Found 0010-Fix-using-large-PCH.patch
  -> Found 0011-Enable-shared-gnat-implib.patch
  -> Found 0014-clone_function_name_1-Retain-any-stdcall-suffix.patch
  -> Found 0016-gcc-7-branch-disable-weak-refs-in-libstdc++.patch
  -> Found 0017-gcc-7-branch-Enable-std-experimental-filesystem.patch
  -> Found 0018-gcc-7-branch-Enable-a-native-GCC-to-color-diagnostic-messages-sen.patch
  -> Found 0019-gcc-8-branch-Backport-patches-for-std-filesystem-from-master.patch
==> Validating source files with sha256sums...
    gcc ... Skipped
    0002-Relocate-libintl.patch ... Passed
    0003-Windows-Follow-Posix-dir-exists-semantics-more-close.patch ... Passed
    0004-Windows-Use-not-in-progpath-and-leave-case-as-is.patch ... Passed
    0005-Windows-Don-t-ignore-native-system-header-dir.patch ... Passed
    0006-Windows-New-feature-to-allow-overriding.patch ... Passed
    0007-Build-EXTRA_GNATTOOLS-for-Ada.patch ... Passed
    0008-Prettify-linking-no-undefined.patch ... Passed
    0010-Fix-using-large-PCH.patch ... Passed
    0011-Enable-shared-gnat-implib.patch ... Passed
    0014-clone_function_name_1-Retain-any-stdcall-suffix.patch ... Passed
    0016-gcc-7-branch-disable-weak-refs-in-libstdc++.patch ... Passed
    0017-gcc-7-branch-Enable-std-experimental-filesystem.patch ... Passed
    0018-gcc-7-branch-Enable-a-native-GCC-to-color-diagnostic-messages-sen.patch ... Passed
    0019-gcc-8-branch-Backport-patches-for-std-filesystem-from-master.patch ... Passed
==> Extracting sources...
  -> Creating working copy of gcc git repo...
Cloning into 'gcc'...
done.
Updating files: 100% (101155/101155), done.
fatal: 'origin/gcc-8' is not a commit and a branch 'makepkg' cannot be created from it
==> ERROR: Failure while creating working copy of gcc git repo
    Aborting...

**Comment by lhmouse** [comment]
https://github.com/lhmouse/MINGW-packages/blob/8d18f0937ef617315fd332fe93177f6a0ca046c2/mingw-w64-gcc-git/PKGBUILD#L48

**Comment by labba** [comment]
thanks.

i think i had it .. nothing working well .. everytime something else is not working .. :-(

can you please find time to upload your 8.3.0 release so i can download it?


i have changed it to 
_branch=releases/gcc-8

now getting this error: 

make[3]: Entering directory '/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32/x86_64-w64-mingw32/libstdc++-v3/include'
echo timestamp > stamp-pb
echo timestamp > stamp-host
make[3]: [Makefile:1675: x86_64-w64-mingw32/bits/largefile-config.h] Error 1 (ignored)
make[3]: [Makefile:1677: x86_64-w64-mingw32/bits/largefile-config.h] Error 1 (ignored)
echo 0 > stamp-namespace-version
echo 0 > stamp-visibility
echo 1 > stamp-extern-template
echo 1 > stamp-dual-abi
echo 1 > stamp-cxx11-abi
echo 1 > stamp-allocator-new
echo 'define _GLIBCXX_USE_FLOAT128 1' > stamp-float128
sed -e '/^#pragma/b' \
    -e '/^#/s/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_][ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*\)/_GLIBCXX_\1/g' \
    -e 's/_GLIBCXX_SUPPORTS_WEAK/__GXX_WEAK__/g' \
    -e 's/_GLIBCXX___MINGW32_GLIBCXX___/__MINGW32__/g' \
    -e 's,^#include "\(.*\)",#include <bits/\1>,g' \
    < /home/labba/MINGW-packages/mingw-w64-gcc-git/src/gcc/libstdc++-v3/../libgcc/gthr.h > x86_64-w64-mingw32/bits/gthr.h
sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
    -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
    < /home/labba/MINGW-packages/mingw-w64-gcc-git/src/gcc/libstdc++-v3/../libgcc/gthr-single.h > x86_64-w64-mingw32/bits/gthr-single.h
sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
    -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
    -e 's/SUPPORTS_WEAK/__GXX_WEAK__/g' \
    -e 's/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*USE_WEAK\)/_GLIBCXX_\1/g' \
    < /home/labba/MINGW-packages/mingw-w64-gcc-git/src/gcc/libstdc++-v3/../libgcc/gthr-posix.h > x86_64-w64-mingw32/bits/gthr-posix.h
sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
    -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
    -e 's/SUPPORTS_WEAK/__GXX_WEAK__/g' \
    -e 's/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*USE_WEAK\)/_GLIBCXX_\1/g' \
    -e 's,^#include "\(.*\)",#include <bits/\1>,g' \
    < /home/labba/MINGW-packages/mingw-w64-gcc-git/src/gcc/libstdc++-v3/../libgcc/gthr-posix.h > x86_64-w64-mingw32/bits/gthr-default.h
make[3]: Leaving directory '/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32/x86_64-w64-mingw32/libstdc++-v3/include'
make[2]: Leaving directory '/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32'
make[1]: *** [Makefile:21392: stage1-bubble] Error 2
make[1]: Leaving directory '/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32'
make: *** [Makefile:949: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by lhmouse** [comment]
No I don't keep old archives.

Old patches (such as [this](https://github.com/lhmouse/MINGW-packages/blob/8d18f0937ef617315fd332fe93177f6a0ca046c2/mingw-w64-gcc-git/9000-gcc-8-branch-Added-mcf-thread-model-support-from-mcfgthread.patch)) are kept archived in the repository but they will not be updated. I suspect they should continue to apply. My best advice is to copy the one for your branch elsewhere, check the commit out  (as you've figured out), move the patch into your local working tree, then edit `PKGBUILD` to include that patch.

**Comment by labba** [comment]
can you help and do this for me ? i really need the 8.3.0

you saw that i have give it a real try from setting the enviroment to trying to resolve those stuff.. its just taking too long ..

**Comment by lhmouse** [comment]
Try the `master_2018-04-26` branch. You are lucky enough that I happen to have created an old snapshot.

**Comment by labba** [comment]
ok so i have cloned it

> git clone -b master_2018-04-26 https://github.com/lhmouse/MINGW-packages.git
> cd MINGW-packages/mingw-w64-mcfgthread-git
> makepkg-mingw

after sucessful build changed the mingw-w64-gcc-git 
from this:

> _branch=gcc-8-branch
> _realpkgver="$(git archive --remote=git://gcc.gnu.org/git/gcc.git refs/heads/${_branch}:gcc/ BASE-VER | tar -xO)"

to this:

> _branch=gcc-8
> _realpkgver="$(git archive --remote=git://gcc.gnu.org/git/gcc.git refs/heads/releases/${_branch}:gcc/ BASE-VER | tar -xO)"

then gone to compile gcc-git folder and gotten the following error:

> # makepkg-mingw
> ==> Making package: mingw-w64-gcc-mcf r161313.86f2f767ddf-1 (Mon, Jun 29, 2020  9:37:25 AM)
> ==> Checking runtime dependencies...
> ==> Missing dependencies:
>   -> mingw-w64-x86_64-mcfgthread-libs
> ==> Checking buildtime dependencies...
> ==> Missing dependencies:
>   -> mingw-w64-x86_64-mcfgthread
> ==> ERROR: Could not resolve all dependencies.

**Comment by labba** [comment]
ok so i have cloned it

> git clone -b master_2018-04-26 https://github.com/lhmouse/MINGW-packages.git
> cd MINGW-packages/mingw-w64-mcfgthread-git
> makepkg-mingw
> pacman -U *.tar.zst

after successful build changed the mingw-w64-gcc-git "PKGBUILD" to point the the release of gcc-8
then gone to compile gcc-git folder and gotten the following error:

> make[3]: Entering directory '/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32/x86_64-w64-mingw32/libstdc++-v3/include'
> echo timestamp > stamp-pb
> echo timestamp > stamp-host
> make[3]: [Makefile:1675: x86_64-w64-mingw32/bits/largefile-config.h] Error 1 (ignored)
> make[3]: [Makefile:1677: x86_64-w64-mingw32/bits/largefile-config.h] Error 1 (ignored)
> echo 0 > stamp-namespace-version
> echo 0 > stamp-visibility
> echo 1 > stamp-extern-template
> echo 1 > stamp-dual-abi
> echo 1 > stamp-cxx11-abi
> echo 1 > stamp-allocator-new
> echo 'define _GLIBCXX_USE_FLOAT128 1' > stamp-float128
> sed -e '/^#pragma/b' \
>     -e '/^#/s/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_][ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*\)/_GLIBCXX_\1/g' \
>     -e 's/_GLIBCXX_SUPPORTS_WEAK/__GXX_WEAK__/g' \
>     -e 's/_GLIBCXX___MINGW32_GLIBCXX___/__MINGW32__/g' \
>     -e 's,^#include "\(.*\)",#include <bits/\1>,g' \
>     < /home/labba/MINGW-packages/mingw-w64-gcc-git/src/gcc/libstdc++-v3/../libgcc/gthr.h > x86_64-w64-mingw32/bits/gthr.h
> sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
>     -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
>     < /home/labba/MINGW-packages/mingw-w64-gcc-git/src/gcc/libstdc++-v3/../libgcc/gthr-single.h > x86_64-w64-mingw32/bits/gthr-single.h
> sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
>     -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
>     -e 's/SUPPORTS_WEAK/__GXX_WEAK__/g' \
>     -e 's/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*USE_WEAK\)/_GLIBCXX_\1/g' \
>     < /home/labba/MINGW-packages/mingw-w64-gcc-git/src/gcc/libstdc++-v3/../libgcc/gthr-posix.h > x86_64-w64-mingw32/bits/gthr-posix.h
> sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
>     -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
>     -e 's/SUPPORTS_WEAK/__GXX_WEAK__/g' \
>     -e 's/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*USE_WEAK\)/_GLIBCXX_\1/g' \
>     -e 's,^#include "\(.*\)",#include <bits/\1>,g' \
>     < /home/labba/MINGW-packages/mingw-w64-gcc-git/src/gcc/libstdc++-v3/../libgcc/config/i386/gthr-mcf.h > x86_64-w64-mingw32/bits/gthr-default.h
> make[3]: Leaving directory '/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32/x86_64-w64-mingw32/libstdc++-v3/include'
> make[2]: Leaving directory '/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32'
> make[1]: *** [Makefile:21392: stage1-bubble] Error 2
> make[1]: Leaving directory '/home/labba/MINGW-packages/mingw-w64-gcc-git/src/build-x86_64-w64-mingw32'
> make: *** [Makefile:949: all] Error 2
> ==> ERROR: A failure occurred in build().
>     Aborting...

**Comment by lhmouse** [comment]
Try `makepkg-mingw -L` to keep build logs. Because `make` runs multiple jobs, the error might be overwhelmed by other outputs, prior to the final failure.

**Comment by labba** [comment]
first i want to say to you : Thank you very much ! i never expected such amazing support and help.

now, i have finished executing it again and here is the log attached:
[mingw-w64-gcc-mcf-r163279.799948c9986-1-x86_64-build.log](https://github.com/lhmouse/MINGW-packages/files/4846452/mingw-w64-gcc-mcf-r163279.799948c9986-1-x86_64-build.log)

and the prepare log:
[mingw-w64-gcc-mcf-r163279.799948c9986-1-x86_64-prepare.log](https://github.com/lhmouse/MINGW-packages/files/4846463/mingw-w64-gcc-mcf-r163279.799948c9986-1-x86_64-prepare.log)

and the version log:
[mingw-w64-gcc-mcf-r163279.799948c9986-1-x86_64-pkgver.log](https://github.com/lhmouse/MINGW-packages/files/4846464/mingw-w64-gcc-mcf-r163279.799948c9986-1-x86_64-pkgver.log)

**Comment by lhmouse** [comment]
```text

In file included from ../../../gcc/libgomp/oacc-parallel.c:30:
../../../gcc/libgomp/oacc-parallel.c:216:18: error: too many arguments for format [-Werror=format-extra-args]
   gomp_debug (0, "%s: mapnum=%"PRIu64", hostaddrs=%p, size=%p, kinds=%p\n",
                  ^~~~~~~~~~~~~~
../../../gcc/libgomp/libgomp.h:109:29: note: in definition of macro 'gomp_debug'
       (gomp_debug) ((KIND), __VA_ARGS__); \
                             ^~~~~~~~~~~

```

**Comment by lhmouse** [comment]
Probably you need this patch <https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gcc-git/0020-libgomp-Don-t-hard-code-MS-printf-attributes.patch>.

This is a breakage caused by recent mingw-w64 updates. You need to place this patch along with others, edit `PKGBUILD` to include and apply it (there are _2_ locations where you need to add it). Then run `updpkgsums` to update checksums. This should make it build again.

(This is yet another reason why I don't want to keep old archives. The fact that MSYS2 uses a rolling CRT makes it impossible to keep archives that 'just work'; I may keep archives but they are going to cease to build sooner or later. There is little point in backporting new patches to them, unless I find someone to test them constantly.)

**Comment by labba** [comment]
i understand what you are saying in regards to source, but  i meant to keep repository of compiled binary. is there a chance you compile the 8.3.0 complete package binary like you post on your website ?

in continue to my efforts,  i have successfully now finished the compilation with the new patch you gave me after i have added it.

now for the last part i'm confused, i'm looking at your zip files (binary) and the folder structure is different then what i got.

the out put of the "mingw-w64-gcc-git\src" is new folders:

> - build-i686-w64-mingw32
> - build-x86_64-w64-mingw32
> - gcc
> - mingw32
> - mingw64

all i have to do is just copy the "build-i686-w64-mingw32" into mingw32 ? and same goes for "build-x86_64-w64-mingw32" into mingw64 ?


i'm still missing a lot of directories i see in your final zip file like "etc" , "libexec"  and more.. 
how do i make the entire pack like you are doing automatically ? are you using some script?

**Comment by lhmouse** [comment]
You install built packages with `pacman -U <path>...`. Back to **GCC 8** era packages are `.tar.xz` files, but now they have migrated to `.tar.zst`, although **pacman** accepts both.

The archives I upload are created from `/mingw32` and `/mingw64` respectively. I have local scripts that pack the directory trees, calculate checksums of them, upload them and move them to the correct location.

**Comment by labba** [comment]
my final end goal is to create like you a package and compile gcc-8 with "--enable-plugin" .. 

sorry for the ignorance, but i don't understand.

so i have successful compilation here:

> C:\msys64\home\labba\MINGW-packages\mingw-w64-gcc-git

i know i can download mingw from the repo here:
http://repo.msys2.org/mingw/x86_64/

so i have download the:
mingw-w64-x86_64-gcc-8.3.0-2-any.pkg.tar.xz


but still i dont see any folder there that it's name is "libexec" for example .. from where it comes from ?

**Comment by lhmouse** [comment]
```text
E:\>pacman -F /mingw32/libexec/
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-clang-analyzer 10.0.0-2
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-creduce 2.10.0-1
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-dbus-glib 0.110-1
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-emacs 26.3-3
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-geany 1.36.0-2
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-geocode-glib 3.26.2-1
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-glib-networking 2.64.3-1
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-gnome-calculator 3.36.0-1
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-gnuplot 5.2.8-1
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-gprbuild-gpl 2020.0.43e55df-1
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-gstreamer 1.16.2-1
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-json-glib 1.4.4-1
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-libvirt 5.9.0-1
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-mecab 0.996-2
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-p11-kit 0.23.20-2
mingw32/libexec/ is owned by mingw32/mingw-w64-i686-qbs 1.16.0-1

```

**Comment by labba** [comment]
i still don't understand what you mean:

pacman -U <path>.... Back to GCC 8  ---- >> back to what path ? 

can you share your build scripts so i can understand all the path references you automatically build ?

**Comment by lhmouse** [comment]
The arguments to `pacman -U` are paths to packages that you have just built, which should look like `mingw-w64-i686-gcc-mcf-...-1-any.pkg.tar.xz` and `mingw-w64-x86_64-gcc-mcf-...-1-any.pkg.tar.xz`.

`makepkg-mingw` is enough for building GCC itself. The other  scripts are only for packaging & uploading.

**Comment by labba** [comment]
so what do you usually pack other then GCC in the "pacman -U"  ?

**Comment by lhmouse** [comment]
The point is that once you have a package built, you install it into your local MSYS2 system. After all necessary packages are upgraded (for me they are `mingw-w64-{i686,x86_64}-{crt,headers,gcc,gdb}-git`), you create an archive from your local `/mingw32` directory and one from your local `/mingw64` directory.

This is the script I use to create packages on <https://gcc-mcf.lhmouse.com> (note it requires the `p7zip` package):

```bash
#!/bin/bash -e

function do_package()
  {
    _arch="$1"
    _name="$2"

    pacman -Q | grep -E "^mingw-w64-${_arch}-" > "${_name}-packages.txt"
    rm -f -- "${_name}.7z"
    7zr a -aoa -mmt"$(nproc)" -- "${_name}.7z" "/${_name}" "${_name}-packages.txt"
  }

do_package i686   mingw32
do_package x86_64 mingw64
```

**Comment by labba** [comment]
so after compilation of gcc-git i have tried the following pacman -U command:

```
MSYS ~/MINGW-packages/mingw-w64-gcc-git
# pacman -U *.tar.zst
loading packages...
resolving dependencies...
looking for conflicting packages...
:: mingw-w64-i686-gcc-mcf and mingw-w64-i686-gcc are in conflict. Remove mingw-w64-i686-gcc? [Y/n] Y
:: mingw-w64-x86_64-gcc-mcf and mingw-w64-x86_64-gcc are in conflict. Remove mingw-w64-x86_64-gcc? [Y/n] Y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing mingw-w64-x86_64-gcc breaks dependency 'mingw-w64-x86_64-gcc=10.1.0-3' required by mingw-w64-x86_64-gcc-ada
:: removing mingw-w64-x86_64-gcc breaks dependency 'mingw-w64-x86_64-gcc=10.1.0-3' required by mingw-w64-x86_64-gcc-fortran
:: removing mingw-w64-x86_64-gcc breaks dependency 'mingw-w64-x86_64-gcc=10.1.0-3' required by mingw-w64-x86_64-gcc-objc

```

so i have seen this issue here:
https://github.com/msys2/MINGW-packages/issues/5434

and removed the ada and fortran and objc
```
pacman -R --noconfirm mingw-w64-x86_64-gcc-fortran || true;
pacman -R --noconfirm mingw-w64-i686-gcc-ada mingw-w64-i686-gcc-objc || true;
pacman -R --noconfirm mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-objc || true;
pacman -R --noconfirm mingw-w64-x86_64-gcc || true;
pacman -R --noconfirm mingw-w64-x86_64-gcc || true;
```

and after that re-tried and got this:

```
MSYS ~/MINGW-packages/mingw-w64-gcc-git
# pacman -U *.tar.zst
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (4) mingw-w64-i686-gcc-mcf-r163283.3a3635a716d-1  mingw-w64-i686-gcc-mcf-libs-r163283.3a3635a716d-1
             mingw-w64-x86_64-gcc-mcf-r163283.3a3635a716d-1
             mingw-w64-x86_64-gcc-mcf-libs-r163283.3a3635a716d-1

Total Installed Size:  354.35 MiB

:: Proceed with installation? [Y/n] Y
(4/4) checking keys in keyring                                     [####################################] 100%
(4/4) checking package integrity                                   [####################################] 100%
(4/4) loading package files                                        [####################################] 100%
(4/4) checking for file conflicts                                  [####################################] 100%
error: failed to commit transaction (conflicting files)
mingw-w64-i686-gcc-mcf-libs: /mingw32/bin/libatomic-1.dll exists in filesystem (owned by mingw-w64-i686-gcc-libs)
mingw-w64-i686-gcc-mcf-libs: /mingw32/bin/libgomp-1.dll exists in filesystem (owned by mingw-w64-i686-gcc-libs)
mingw-w64-i686-gcc-mcf-libs: /mingw32/bin/libquadmath-0.dll exists in filesystem (owned by mingw-w64-i686-gcc-libs)
mingw-w64-i686-gcc-mcf-libs: /mingw32/bin/libssp-0.dll exists in filesystem (owned by mingw-w64-i686-gcc-libs)
mingw-w64-i686-gcc-mcf-libs: /mingw32/bin/libstdc++-6.dll exists in filesystem (owned by mingw-w64-i686-gcc-libs)
mingw-w64-x86_64-gcc-mcf-libs: /mingw64/bin/libatomic-1.dll exists in filesystem (owned by mingw-w64-x86_64-gcc-libs)
mingw-w64-x86_64-gcc-mcf-libs: /mingw64/bin/libgcc_s_seh-1.dll exists in filesystem (owned by mingw-w64-x86_64-gcc-libs)
mingw-w64-x86_64-gcc-mcf-libs: /mingw64/bin/libgomp-1.dll exists in filesystem (owned by mingw-w64-x86_64-gcc-libs)
mingw-w64-x86_64-gcc-mcf-libs: /mingw64/bin/libquadmath-0.dll exists in filesystem (owned by mingw-w64-x86_64-gcc-libs)
mingw-w64-x86_64-gcc-mcf-libs: /mingw64/bin/libssp-0.dll exists in filesystem (owned by mingw-w64-x86_64-gcc-libs)
mingw-w64-x86_64-gcc-mcf-libs: /mingw64/bin/libstdc++-6.dll exists in filesystem (owned by mingw-w64-x86_64-gcc-libs)
Errors occurred, no packages were upgraded.

```

**Comment by lhmouse** [comment]
Install with `pacman -U --overwrite="*"` (note the `*` must be escaped to prevent shell expansion).

Note this overwrites some files from `mingw-w64-{i686,x86_64}-gcc-libs`. Uninstalling the latter may break other packages so it's unfeasible. Re-installation of `gcc-mcf-libs` is necessary if the latter ones get upgraded.

**Comment by labba** [comment]
finally it's working and done !!! 
after the installation i have run your script from the same location and it worked like a charm!

you are amazing !!!! thank you very much !!!

is there a  place you accept donations ? i would like to support your  work (as much as i can .. )

**Comment by lhmouse** [comment]
That's very kind of you.. but at the moment I don't have a PayPal account. Maybe in the future. :joy:

**Comment by labba** [comment]
thanks again!

**Comment by labba** [comment]
btw, 
as just future recommendation i think it's good idea to have snapshot per each major GCC version (i don't know if you already doing it ...)

**Comment by lhmouse** [comment]
There are some indirect dependencies (for example GDB <- Python). As other packages depend on `gcc-libs` downgrading GCC without affecting other packages is not feasible.
