### ISSUE TITLE
mcfgthread-git builds fails

### ISSUE THREAD

**Issue by expnkx** [lhmouse/MINGW-packages#7]
unlvs@DESKTOP-DFHPDC1 MSYS ~/MINGW-packages/mingw-w64-mcfgthread-git
$ makepkg-mingw
==> ERROR: Missing package_mingw-w64-x86_64-mcfgthread-git() function for split package 'mingw-w64-x86_64-mcfgthread-git'
==> ERROR: Missing package_mingw-w64-x86_64-mcfgthread-libs-git() function for split package 'mingw-w64-x86_64-mcfgthread-libs-git'
![image](https://user-images.githubusercontent.com/57303909/94760397-6293b580-0370-11eb-8f80-71332d563afa.png)

Change the last few lines to this and it builds.

# Wrappers for package functions

# 32-bit wrappers
package_mingw-w64-i686-mcfgthread-git() {
  package_mingw-w64-mcfgthread
}
package_mingw-w64-i686-mcfgthread-libs-git() {
  package_mingw-w64-mcfgthread-libs
}

# 64-bit wrappers
package_mingw-w64-x86_64-mcfgthread-git() {
  package_mingw-w64-mcfgthread
}
package_mingw-w64-x86_64-mcfgthread-libs-git() {
  package_mingw-w64-mcfgthread-libs
}

**Comment by lhmouse** [comment]
Please submit this to <https://github.com/msys2/MINGW-packages>.

**Comment by lhmouse** [comment]
This has been fixed now.
