### ISSUE TITLE
Compiling OpenCV with your Compiler stops with error that vidcap.h is missing

### ISSUE THREAD

**Issue by Bosi1024** [lhmouse/MINGW-packages#9]
Hi,

I am not able to compile OpenCV (4.6.0) with your compiler suite with videoio enabled; it errors out with vidcap.h not found which seems to be part of MinGWs w32api (and also part of the Windows SDK - MS Media Foundation). Could you point me in the right direction on how to solve the problem?

Kind Regards

**Comment by lhmouse** [comment]
It looks like this header has to be added in mingw-w64 (not exclusive to this project). @Biswa96 Would please take care of it?

**Comment by Bosi1024** [comment]
Thank you very much for the quick answer!
 If I can be of any assistance, I am glad to help!

**Comment by Biswa96** [comment]
@Bosi1024 We are in a forked repository. It may be better if we can continue the discussion in the main repo. Can you provide which commands you used to compile opencv? opencv needs some patching for mingw environment, see https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-opencv

**Comment by Biswa96** [comment]
BTW, I have added vidcap.h in my test setup but opencv can not be compiled due to this error:

```
opencv/modules/videoio/src/cap_obsensor/obsensor_stream_channel_msmf.hpp:106:27: error: could not convert template argument 'cv::obsensor::ComPtr<IMFAttributes>::__T_IID_getter' from 'const IID& (cv::obsensor::ComPtr<IMFAttributes>::)()' {aka 'const GUID& (cv::obsensor::ComPtr<IMFAttributes>::)()'} to 'const IID& (*)()' {aka 'const GUID& (*)()'}
  106 |     _COM_SMARTPTR_TYPEDEF(T, __uuidof(T));
      |                           ^
```

I can not decipher it 😭

**Comment by lhmouse** [comment]
> I can not decipher it 😭 

The error was about conversion from a non-static member function to a plain function pointer. The referenced function may have to be static.

**Comment by Biswa96** [comment]
I have sent a patch to upstream mingw-w64 to add vidcap.h file. Here is the link to the mail https://sourceforge.net/p/mingw-w64/mailman/message/37693654/

**Comment by lhmouse** [comment]
> I have sent a patch to upstream mingw-w64 to add vidcap.h file. Here is the link to the mail https://sourceforge.net/p/mingw-w64/mailman/message/37693654/

Thank you. I have committed that patch.

@Bosi1024 As I build the master branch of mingw-w64, this will be available in the next snapshot, presumably around 08-23. Please wait a few days.

**Comment by Biswa96** [comment]
Many changes are still required in upstream opencv also which need more time.

**Comment by Biswa96** [comment]
vidcap.h header is now available in msys2's mingw headers package. The file list can be found here https://packages.msys2.org/package/mingw-w64-x86_64-headers-git?repo=mingw64.

**Comment by Bosi1024** [comment]
Thank you so much!

I will try it out as soon as possible

**Comment by Bosi1024** [comment]
Hi again,

I've used the snapshot from 08-23 (msvcrt, if that is correct) to build OpenCV (current git master + opencv contrib modules) and came across the same compile error as @Biswa96 .

I've not used any patches as mentioned above, yet.

**Comment by Biswa96** [comment]
I'm not seeing any error related to vidcap.h in opencv 4.x branch. Make sure that header file is present in your system. Also while configuring opencv with cmake, it shows a message if vidcap.h is present. 

opencv as a whole can not be compiled without some patches in mingw environment. Those can be found in msys2's mingw-packages repository.

**Comment by Bosi1024** [comment]
Then there is something missing on my side. I'm using @lhmouse mingw-w64 binaries from 08-23 (latest release) which includes vidcap.h.

I'm stumbling across this error:

```
opencv\modules\videoio\src\cap_obsensor\obsensor_stream_channel_msmf.hpp:106:27: error: could not convert template argument 'cv::obsensor::ComPtr<IMFActivate>::__T_IID_getter' from 'const IID& (cv::obsensor::ComPtr<IMFActivate>::)()' {aka 'const GUID& (cv::obsensor::ComPtr<IMFActivate>::)()'} to 'const IID& (*)()' {aka 'const GUID& (*)()'}
  106 |     _COM_SMARTPTR_TYPEDEF(T, __uuidof(T));
```

which seems to be the same error you encountered before.

**Comment by lhmouse** [comment]
We had some discussion about this macro. The quick fix would be to move all invocations of `_COM_SMARTPTR_TYPEDEF` outside their enclosing classes (so they have namespace scope). Such errors should go away thereafter.

**Comment by Biswa96** [comment]
This thread may help with that issue https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/CALK-3mLse2MebGKcFVSksAd0DT3_12buNv2rz9P1eH3F3V_KHw@mail.gmail.com/. ~~There is no actual fix for that issue yet.~~

Try to add `-DWITH_MSMF=OFF` option with cmake while configuring opencv.

**Comment by lhmouse** [comment]
@Bosi1024 My builds are packaged with newest MSYS2 packages at that time point. In other words, except that `mingw-w64-<ARCH>-{gcc,gdb}` are built from the latest release branches and `mingw-w64-<ARCH>-{{headers,crt,tools}-git,mcfgthread}` are built from their master branches (because we have control), there's no difference between all the other packages and MSYS2 ones.

**Comment by Bosi1024** [comment]
Hi,

I checked that -DWITH_MSMF=OFF is set in the opencv cmake configuration. In my case, this seems to be the default as I didn't touch this configuration value at all.

**Comment by Biswa96** [comment]
Oops, my mistake. That obsensor can be disabled with `-DWITH_OBSENSOR=OFF` option in cmake configuration.

**Comment by Bosi1024** [comment]
Thank you very much, setting `-DWITH_OBSENSOR=OFF` did the trick. I am somewhat confused why it was enabled by default.
